with-expecter: true
dir: mocks/{{ replaceAll .PackagePath "internal" "internal_" }}
packages:
  github.com/gitopia/git-server/internal/app:
    interfaces:
      QueryService:
  github.com/gitopia/git-server/pkg/spheron:
    interfaces:
      SpheronClientInterface:
