web_server_port = 5000
gitopia_grpc_url = "grpc.gitopia.dev:9090"
git_dir = "/var/repos"
attachment_dir = "/var/attachments"
tm_addr = "http://grpc.gitopia.dev:26657"
key_name = "git-server"
keyring_dir = "/home/ubuntu/git-server"
gas_prices = "0.001utlore"
chain_id = "gitopia-janus-devnet-3"
