WEB_SERVER_PORT = 5000
GITOPIA_ADDR = "grpc.devnet.gitopia.com:9090"
GIT_DIR = "/var/repos"
LFS_OBJECTS_DIR = "/var/lfs-objects"
GIT_SERVER_EXTERNAL_ADDR = "https://server.devnet.gitopia.com"
ATTACHMENT_DIR = "/var/attachments"
TM_ADDR = "https://rpc.devnet.gitopia.com:443"
WORKING_DIR = "/home/ubuntu/git-server/"
GAS_PRICES = "0.001ulore"
CHAIN_ID = "gitopia-janus-devnet-4"
FEE_GRANTER=""

# IPFS Configuration
IPFS_CLUSTER_PEER_HOST = "ipfs-cluster"
IPFS_CLUSTER_PEER_PORT = "9094"
IPFS_HOST = "ipfs"
IPFS_PORT = "5001"
ENABLE_EXTERNAL_PINNING = false
PINATA_JWT = ""