WEB_SERVER_PORT = 5001
GITOPIA_ADDR = "localhost:9090"
GIT_DIR = "/var/repos"
ATTACHMENT_DIR = "/var/attachments"
TM_ADDR = "http://localhost:26657"
WORKING_DIR = "/tmp/git-server"
GAS_PRICES = ""
CHAIN_ID = "gitopia"
