WEB_SERVER_PORT = 5000
GITOPIA_ADDR = "grpc.devnet.gitopia.com:9090"
GIT_REPOS_DIR = "/var/repos"
LFS_OBJECTS_DIR = "/var/lfs-objects"
ATTACHMENT_DIR = "/var/attachments"
TM_ADDR = "https://rpc.devnet.gitopia.com:443"
WORKING_DIR = "/home/ubuntu/gitopia-storage/"
GAS_PRICES = "0.001ulore"
CHAIN_ID = "gitopia-janus-devnet-4"

# IPFS Configuration
IPFS_CLUSTER_PEER_HOST = "ipfs-cluster"
IPFS_CLUSTER_PEER_PORT = "9094"
IPFS_HOST = "ipfs"
IPFS_PORT = "5001"
ENABLE_EXTERNAL_PINNING = false
PINATA_JWT = ""

# Cache Configuration
CACHE_REPO_MAX_AGE = "24h"
CACHE_REPO_MAX_SIZE = 10737418240    # 10GB in bytes
CACHE_ASSET_MAX_AGE = "168h"         # Maximum age for asset cache entries (7 days)
CACHE_ASSET_MAX_SIZE = 5368709120    # Maximum size for asset cache (5GB in bytes)
CACHE_LFS_MAX_AGE = "720h"           # Maximum age for LFS object cache entries (30 days)
CACHE_LFS_MAX_SIZE = 53687091200     # Maximum size for LFS object cache (50GB in bytes)
CACHE_CLEAR_INTERVAL = "1h"