WEB_SERVER_PORT = 5000
GITOPIA_ADDR = "grpc.gitopia.com:9090"
GIT_DIR = "/var/repos"
ATTACHMENT_DIR = "/var/attachments"
TM_ADDR = "http://grpc.gitopia.com:26657"
WORKING_DIR = "/home/ubuntu/git-server"
GAS_PRICES = "0.001ulore"
CHAIN_ID = "gitopia-janus-testnet-2"
