web_server_port = 5000
gitopia_grpc_url = "grpc.gitopia.com:9090"
git_dir = "/var/repos"
attachment_dir = "/var/attachments"
tm_addr = "http://grpc.gitopia.com:26657"
keyring_dir = "/home/ubuntu/git-server"
gas_prices = "0.001ulore"
chain_id = "gitopia-janus-testnet-2"
