web_server_port = 5001
gitopia_grpc_url = "localhost:9090"
git_dir = "/var/repos"
attachment_dir = "/var/attachments"
tm_addr = "http://localhost:26657"
keyring_dir = "/Users/faza/Code/git-server"
gas_prices = "0.001utlore"
chain_id = "gitopia"
