WEB_SERVER_PORT = 5000
GITOPIA_ADDR = "host.docker.internal:9100"
GIT_DIR = "/var/repos"
LFS_OBJECTS_DIR = "/var/lfs-objects"
GIT_SERVER_EXTERNAL_ADDR = "http://localhost:5001"
ATTACHMENT_DIR = "/var/attachments"
TM_ADDR = "http://host.docker.internal:26667"
WORKING_DIR = "/src/app/"
GAS_PRICES = "0.001ulore"
CHAIN_ID = "localgitopia"
FEE_GRANTER="gitopia12sjhqc3rqgvu3zpg8ekmwl005rp4ys58ekqg89"
