WEB_SERVER_PORT = 5000
GITOPIA_ADDR = "gitopia-grpc.polkachu.com:11390"
GIT_DIR = "/var/repos"
LFS_OBJECTS_DIR = "/var/lfs-objects"
GIT_SERVER_EXTERNAL_ADDR = "https://server.gitopia.com"
ATTACHMENT_DIR = "/var/attachments"
TM_ADDR = "https://gitopia-rpc.polkachu.com:443"
WORKING_DIR = "/home/ubuntu/git-server/"
GAS_PRICES = "0.001ulore"
CHAIN_ID = "gitopia"
FEE_GRANTER="gitopia13ashgc6j5xle4m47kqyn5psavq0u3klmscfxql"
