GITOPIA_ADDR = "localhost:9100"
GIT_REPOS_DIR = "/var/repos"
ATTACHMENT_DIR = "/var/attachments"
TM_ADDR = "http://localhost:26667"
WORKING_DIR = "/tmp/test"
GAS_PRICES = "0.001ulore"
CHAIN_ID = "gitopia"
GIT_SERVER_HOST = "http://localhost:5001"

# IPFS Configuration
IPFS_CLUSTER_PEER_HOST = "localhost"
IPFS_CLUSTER_PEER_PORT = "9094"
IPFS_HOST = "localhost"
IPFS_PORT = "5003"
